#Hugo configuration
title = "wqedf"
baseURL = "https:\/\/ersdcf.dsf.ere"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true
galleryChannelIds = "83052333,85595609,85601876"

[params]
loginId = "1758823"
subfolder = ""
firstpartycookies = true
cookiedomain = "dsf.ere"
