#Hugo configuration
title = "Bed Bath USA Videos"
baseURL = "https:\/\/video.bedbathandbeyond.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true
galleryChannelIds = "83052333,85595609,85601876"

[params]
loginId = "1758166"
subfolder = ""


